# Site settings
title: nemo's dev memos |
headertitle: nemo's dev memos
description: "nemo's dev memos"
url: "https://sykim-ivy.github.io"
author:
  name: "sykim.ivy"
  email: "sykim.ivy@gmail.com"

# Build settings
baseurl: ""
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
